spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=GymProject;encrypt=true;trustServerCertificate=true
spring.datasource.username=gymapp
spring.datasource.password=gymapp
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver