spring.application.name=spring01


# SQL Server 連線設定範例
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=gym;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=gym
spring.datasource.password=gym


# 讓 Hibernate 自動對齊你的資料庫表結構（開發時常用）
# 第一行 是否要讓hibernate改動SQL的結構
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


spring.servlet.encoding.charset=UTF-8
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=64MB

server.servlet.session.timeout=30m

# 以下自訂s
company.name=Brad Big Company
company.tel=04-12345678
name=Brad
file.upload.dir=src/main/resources/static/upload/